### ISSUE TITLE
Values in plots for variable_dropout are not sorted

### ISSUE THREAD

**Issue by agosiewska** [pbiecek/DALEX#9] opened 2018-03-01 22:57 UTC
In the plots for variable_dropout_explainers for multiple models, the variables are not sorted by the Drop-out loss value. This can be seen in the example from the cheatsheet.
![image](https://user-images.githubusercontent.com/18423383/36872530-d95ab564-1da5-11e8-9daf-82c4703463c5.png)

Perhaps it would be worth sorting out them?
When a single model is plotted, the values are sorted.

**Comment by pbiecek** [comment] 2018-03-02 01:46
Variables are sorted along average variable loss across all models.

This way it is easier to compare models because lack of order means that variable importance is different in this model than in others

This should be in the documentation, will work on that

**Comment by pbiecek** [comment] 2018-03-17 12:39
Closing, since it's not a bug

**Closed by pbiecek** 2018-03-17 12:39 UTC
